[tool.poetry]
name = "snake"
version = "0.1.0"
description = ""
authors = ["vkrich <vladislav.krichevsky@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
pygame = "^1.9.6"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]

